# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

3. Create a null vector of size 10 (★☆☆)

In [2]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [3]:
A=np.zeros((10,10))
print()

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
A=np.zeros(10)
A[4]=1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
A=np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [6]:
A=np.arange(50)
A=A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
A= np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [8]:
Zero=np.nonzero([1,2,0,0,4,0])
print(Zero)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [9]:
A=np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [10]:
A=np.random.random((3,3,3))
print(A)

[[[0.97480153 0.07459148 0.03568394]
  [0.17178022 0.75865908 0.90282204]
  [0.50224627 0.53642993 0.90116868]]

 [[0.23105634 0.66975121 0.87696494]
  [0.75138368 0.86220639 0.77923858]
  [0.13386755 0.91391617 0.70806029]]

 [[0.17807323 0.04672888 0.3119504 ]
  [0.61838917 0.83839853 0.86859357]
  [0.88769374 0.02636066 0.08195098]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [11]:
A=np.random.random((10,10))
Amin=A.min()
Amax=A.max()
print(Amin,Amax)

0.029505382826164217 0.9964936009192412


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [12]:
A=np.random.random(30)
a=A.mean()
print(a)

0.4577274994989686


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
A= np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(A)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [14]:
A = np.ones(3)
B = 2*np.ones(3)
C = 3*np.ones(3)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [15]:
A = np.random.uniform(0,10,10)
print (A.astype(int))
print (np.floor(A))
print (np.ceil(A)-1)
print (A - A%1)
print (np.trunc(A))

[2 3 2 3 0 8 8 0 8 2]
[2. 3. 2. 3. 0. 8. 8. 0. 8. 2.]
[2. 3. 2. 3. 0. 8. 8. 0. 8. 2.]
[2. 3. 2. 3. 0. 8. 8. 0. 8. 2.]
[2. 3. 2. 3. 0. 8. 8. 0. 8. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [16]:
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [17]:
def generate():
    for a in range(10):
        yield a
A = np.fromiter(generate(),dtype=float,count=-1)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [18]:
A = np.linspace(0,1,11,endpoint=False)[1:]
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [19]:
A = np.random.random(10)
A.sort()
print(A)

[0.33139943 0.37440798 0.62903879 0.66130499 0.67686014 0.86998739
 0.90371574 0.92147716 0.93202723 0.93725674]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [20]:
A = np.arange(10)
np.add.reduce(A)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [21]:
X = np.random.randint(0,3,6)
Y = np.random.randint(0,3,6)
Z = np.allclose(X,Y)
print(Z)
Z = np.array_equal(X,Y)
print(Z)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [103]:
A = np.ones(5, dtype=int)
A.flags.writeable=False
print(A)
try:
    A[1] = 0   
except Exception as e:
    print('A[1] = 0')

[1 1 1 1 1]
A[1] = 0


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [23]:
A = np.random.random((10,2))
X,Y = A[:,0], A[:,1]
F = np.sqrt(X**2+Y**2)
Z = np.arctan2(Y,X)
print(F)
print(Z)

[0.5860135  1.21789881 0.92481133 0.38946186 0.56742247 0.78684849
 1.02161993 0.88083618 0.15429168 1.04184845]
[1.36302794 0.76673427 0.94327264 0.04010724 0.83006243 0.78415669
 1.05802421 0.09705735 1.15524482 1.06996453]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [24]:
A = np.random.random(10)
A[A.argmax()]=0
print(A)

[0.54392334 0.38237815 0.         0.08456443 0.56480419 0.7524766
 0.1143713  0.59259842 0.2312011  0.33658865]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [25]:
A = np.zeros((5,5), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [26]:
X = np.arange(8)
Y = X + 0.5
R = 1.0/np.subtract.outer(X, Y)
print(np.linalg.det(R))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [27]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).max)
   print(np.iinfo(dtype).min)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).eps)

127
-128
2147483647
-2147483648
9223372036854775807
-9223372036854775808
3.4028235e+38
-3.4028235e+38
1.1920929e-07
1.7976931348623157e+308
-1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [102]:
np.set_printoptions(threshold=float("inf"))
A = np.zeros((10,10))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [29]:
A = np.arange(100)
V = np.random.uniform(0,100)
Z = (np.abs(A-V)).argmin()
print(A[Z])

83


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [30]:
A = np.zeros(10, [ ('position', [ ('x', float),('y', float)]),('color',[ ('r', float),('g', float),('b', float)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [100]:
A = np.random.random((10,2))
X,Y = np.atleast_2d(A[:,0], A[:,1])
Z = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(Z)

[[0.         0.4700164  0.16027805 0.69283037 0.32468564 0.66399724
  0.51703151 0.55944483 0.4200557  0.25077089]
 [0.4700164  0.         0.59044856 0.88159376 0.52174415 0.88011369
  0.91624938 1.01871684 0.38268286 0.23947665]
 [0.16027805 0.59044856 0.         0.57078099 0.46795208 0.77108984
  0.35722694 0.50998632 0.42845128 0.39661053]
 [0.69283037 0.88159376 0.57078099 0.         1.01710651 1.34169063
  0.44155059 0.96248404 0.5034296  0.82332891]
 [0.32468564 0.52174415 0.46795208 1.01710651 0.         0.3778445
  0.8025768  0.61463507 0.67706389 0.30990924]
 [0.66399724 0.88011369 0.77108984 1.34169063 0.3778445  0.
  1.04175461 0.64503423 1.05120418 0.68599485]
 [0.51703151 0.91624938 0.35722694 0.44155059 0.8025768  1.04175461
  0.         0.54233728 0.64145584 0.7483568 ]
 [0.55944483 1.01871684 0.50998632 0.96248404 0.61463507 0.64503423
  0.54233728 0.         0.93779905 0.78218276]
 [0.4200557  0.38268286 0.42845128 0.5034296  0.67706389 1.05120418
  0.64145584 0.937799

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [99]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [98]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  A, 7, 8

                 ,  , 9,10,11
''') 
Z = np.genfromtxt(s, filling_values= 100, delimiter=",", comments="#", dtype=np.int8)
print(Z)

[[  1   2   3   4   5]
 [  6 100 100   7   8]
 [100 100   9  10  11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [34]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [35]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [36]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [37]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.05477038  0.26772007 -0.30201363 -0.08375815  0.13020191  0.26391687
   0.27307757 -0.06907433 -0.4844466  -0.05039408]
 [-0.01585645 -0.09758211  0.44094704  0.13460797 -0.35509798  0.03946295
  -0.26008685  0.08722852 -0.18225311  0.20863003]
 [-0.17813895  0.39886479 -0.47262168  0.23728692  0.10310723  0.26477321
   0.21670171 -0.281958   -0.09566386 -0.19235137]
 [ 0.32210993  0.13315225 -0.19355473 -0.20846584 -0.10502265  0.15183525
  -0.09559506  0.13582274  0.30019271 -0.44047461]
 [ 0.05276707  0.14195092 -0.20422287  0.26566111 -0.1678566  -0.37905774
   0.31652015 -0.27349454  0.28847695 -0.04074445]]


#### 59. How to sort an array by the nth column? (★★☆)

In [97]:
X = np.random.randint(0,10,(3,3))
print(X)
print(X[X[:,1].argsort()])

[[8 8 5]
 [3 1 8]
 [4 1 8]]
[[3 1 8]
 [4 1 8]
 [8 8 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [96]:
A = np.random.randint(0,2,(3,10))
print((~A.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [95]:
X = np.random.uniform(0,1,10)
Y = 0.5
Z = X.flat[np.abs(X - Y).argmin()]
print(Z)

0.6032863260605269


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [92]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
C = np.nditer([A,B,None])
for x,y,z in C: z[...] = x + y
print(C.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [91]:
X = np.ones(10)
Y = np.random.randint(0,len(X),20)
X += np.bincount(Y, minlength=len(X))
print(X)

[5. 8. 3. 2. 2. 1. 2. 3. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [44]:
X = [1,2,3,4,5,6]
Y = [1,3,9,3,4,1]
Z = np.bincount(Y,X)
print(Z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [90]:
w,h = 16,16
X = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
Y = X[...,0]*256*256 + X[...,1]*256 +X[...,2]
n = len(np.unique(Y))
print(np.unique(X))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [46]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[47 59 48 39]
 [35 51 55 61]
 [45 59 49 45]]
[[47 59 48 39]
 [35 51 55 61]
 [45 59 49 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [89]:
A = np.random.uniform(0,1,100)
B = np.random.randint(0,10,100)
A_sums = np.bincount(B, weights=A)
A_counts = np.bincount(B)
A_means = A_sums / A_counts
print(A_means)
import pandas as pd
print(pd.Series(A).groupby(B).mean())

[0.49929049 0.48947653 0.44813285 0.57276116 0.46629379 0.40638652
 0.31576596 0.59707116 0.56483749 0.70478832]
0    0.499290
1    0.489477
2    0.448133
3    0.572761
4    0.466294
5    0.406387
6    0.315766
7    0.597071
8    0.564837
9    0.704788
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [48]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([1.21813543, 1.21967818, 0.73097475, 1.21414552, 1.26430167])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [49]:
A = np.array([1,2,3,4,5])
nz = 3
A0 = np.zeros(len(A) + (len(Z)-1)*(nz))
A0[::nz+1] = A
print(A0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [50]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [51]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [88]:
Z = np.random.randint(0,100,(10,3))
A = np.roll(Z.repeat(2,axis=1),-1,axis=1)
A = A.reshape(len(A)*3,2)
A = np.sort(A,axis=1)
B = A.view( dtype=[('p0',A.dtype),('p1',A.dtype)] )
B = np.unique(B)
print(B)

[( 3,  4) ( 3, 43) ( 4, 43) ( 5, 28) ( 5, 37) ( 6, 83) ( 6, 99) (14, 42)
 (14, 73) (21, 56) (21, 67) (25, 57) (25, 64) (28, 37) (29, 58) (29, 79)
 (35, 60) (35, 68) (42, 73) (56, 67) (57, 64) (58, 79) (59, 70) (59, 93)
 (60, 68) (65, 88) (65, 99) (70, 93) (83, 99) (88, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [53]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [54]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [55]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [56]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.8176553 ,  0.45667202,  0.38749702,  0.0590182 , -0.29719986,
       -0.99695953, -0.27982372, -0.16020039, -0.81178888,  0.53806508,
       -0.99973256, -0.9725168 ,  0.40972518,  0.83388078, -0.8708437 ,
        0.58572103, -0.48016824, -0.87819998, -0.80400828,  0.88770385,
       -0.85176878,  0.61947694, -0.25274117,  0.185655  , -0.1676468 ,
       -0.98679986, -0.02933903, -0.16271742, -0.68252485,  0.81122398,
       -0.06994184, -0.2280696 ,  0.04761339, -0.00588793, -0.08970062,
       -0.60915961,  0.81592476,  0.31315365, -0.95642124,  0.49391463,
        0.64339407,  0.44604373, -0.16013317,  0.94754895,  0.61024207,
        0.39888472, -0.65301737,  0.29883785,  0.9756249 , -0.6329357 ,
        0.23059055,  0.30866402, -0.42576846, -0.99405054,  0.57814498,
       -0.09859521,  0.6012105 , -0.46750793, -0.11149526,  0.30392463,
       -0.20843866,  0.92929441,  0.32437522, -0.79615244, -0.30966675,
        0.49006223,  0.89990731, -0.57486918, -0.71419966,  0.39

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [57]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[15.07646299  5.29056434  7.78625609  2.39871376  7.75562436  6.91447325
  5.16990771  6.86830677  5.05857024  7.4854533 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [58]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.34016006e+01 7.38753394e+00 1.11421431e+01 6.63607618e+00
  7.76935163e+00 5.54685868e+00 1.04915935e+01 1.27525345e+01
  7.52015397e+00 7.77062575e+00]
 [9.91278084e+00 1.12128866e+01 7.35720840e+00 4.38838564e+00
  1.65975525e+00 8.48614047e+00 1.51796073e+01 1.03157201e+01
  2.28943269e+00 1.28026484e+01]
 [7.41718877e+00 1.08050717e+01 4.79740445e+00 2.18083013e+00
  1.33079330e+00 7.77457785e+00 1.50837312e+01 8.06239199e+00
  4.97408844e+00 1.28361414e+01]
 [2.60259045e+00 1.24271232e+00 4.99146422e+00 8.66831661e+00
  8.76950098e+00 4.39987326e+00 3.27806709e+00 2.67415876e+00
  1.40861161e+00 1.16347857e+00]
 [1.09766343e+01 1.09921139e+01 8.46696062e+00 5.25417541e+00
  3.10777378e+00 8.43628037e+00 1.47875600e+01 1.12122568e+01
  6.01239971e-01 1.23408043e+01]
 [2.37333539e+00 1.79790281e+00 7.92295721e-03 3.84180143e+00
  3.78415505e+00 9.87458882e-01 5.91288460e+00 2.18020796e+00
  8.75076951e-01 3.62302854e+00]
 [6.65255011e+00 2.94508692e+00 4.65273196e+00 1.09462326e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [59]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [60]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [61]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [62]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 3]
   [1 2 2]
   [0 3 3]]

  [[3 3 3]
   [2 2 4]
   [3 3 1]]

  [[3 3 2]
   [2 4 1]
   [3 1 0]]

  [[3 2 2]
   [4 1 4]
   [1 0 0]]

  [[2 2 1]
   [1 4 4]
   [0 0 1]]

  [[2 1 3]
   [4 4 1]
   [0 1 3]]

  [[1 3 2]
   [4 1 2]
   [1 3 2]]

  [[3 2 2]
   [1 2 3]
   [3 2 0]]]


 [[[1 2 2]
   [0 3 3]
   [3 3 3]]

  [[2 2 4]
   [3 3 1]
   [3 3 2]]

  [[2 4 1]
   [3 1 0]
   [3 2 4]]

  [[4 1 4]
   [1 0 0]
   [2 4 4]]

  [[1 4 4]
   [0 0 1]
   [4 4 0]]

  [[4 4 1]
   [0 1 3]
   [4 0 2]]

  [[4 1 2]
   [1 3 2]
   [0 2 2]]

  [[1 2 3]
   [3 2 0]
   [2 2 1]]]


 [[[0 3 3]
   [3 3 3]
   [4 1 3]]

  [[3 3 1]
   [3 3 2]
   [1 3 0]]

  [[3 1 0]
   [3 2 4]
   [3 0 2]]

  [[1 0 0]
   [2 4 4]
   [0 2 3]]

  [[0 0 1]
   [4 4 0]
   [2 3 2]]

  [[0 1 3]
   [4 0 2]
   [3 2 0]]

  [[1 3 2]
   [0 2 2]
   [2 0 2]]

  [[3 2 0]
   [2 2 1]
   [0 2 1]]]


 [[[3 3 3]
   [4 1 3]
   [0 0 2]]

  [[3 3 2]
   [1 3 0]
   [0 2 4]]

  [[3 2 4]
   [3 0 2]
   [2 4 2]]

  [[2 4 4]
   [0 2 3]
   [4 2 1]]

  [[4 4 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [63]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 10  9 13  3]
 [10  4  7  5  9]
 [ 9  7  5 42  9]
 [13  5 42  7  2]
 [ 3  9  9  2  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [64]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [65]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [66]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:]
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

SyntaxError: invalid syntax (1863909266.py, line 5)

#### 89. How to get the n largest values of an array (★★★)

In [67]:
A = np.arange(15000)
np.random.shuffle(A)
n=5
print (A[np.argpartition(-A,n)[:n]])

[14998 14995 14996 14997 14999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [86]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    z = np.indices(shape, dtype=int)
    z = z.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        z[:, n] = arrays[n][z[:, n]]
    return z
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [84]:
Y = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
X = np.core.records.fromarrays(X.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(X)

[(b'X', 2.5, 3) (b'Z', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [80]:
x = np.random.random(10)
print(x)
print((x*x*x)[:5])
print(np.power(x,3)[:5])
print(np.einsum('i,i,i->i', x, x, x)[:5]) 

[0.21593592 0.45904058 0.15256258 0.20090297 0.48565956 0.10216072
 0.86850085 0.30940771 0.54633775 0.44820112]
[0.01006873 0.09672823 0.00355095 0.00810885 0.11455019]
[0.01006873 0.09672823 0.00355095 0.00810885 0.11455019]
[0.01006873 0.09672823 0.00355095 0.00810885 0.11455019]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [71]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
Z = np.where(C.any((3,1)).all(1))[0]
print(Z)

[1 2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [72]:
A = np.random.randint(0,5,(10,3))
print(A)
E = np.all(A[:,1:] == A[:,:-1], axis=1)
Z = A[~E]
print(U)
Z = A[A.max(axis=1) != A.min(axis=1),:]
print(Z)

[[4 4 3]
 [2 1 2]
 [4 2 3]
 [4 0 1]
 [4 1 1]
 [1 2 3]
 [0 2 4]
 [3 3 0]
 [0 2 1]
 [2 2 1]]
[[-0.20763431  0.12962118 -0.18938657 -0.29925119 -0.12938875 -0.03805811
  -0.28359499 -0.47776383 -0.4301188  -0.55026481]
 [-0.33088794 -0.20996502 -0.04613105 -0.58788346 -0.35449689  0.40046709
   0.08667145 -0.1189561   0.14418475  0.412552  ]
 [-0.21718279 -0.46131605  0.362017    0.29468599  0.30691607  0.3211181
  -0.27037833 -0.11367684 -0.45208622  0.18547205]
 [-0.41774477  0.16766621 -0.04671235  0.04866347  0.16759974 -0.3402005
  -0.64100739 -0.08438265  0.40609164  0.25705989]
 [-0.28623202  0.35020263 -0.41333637  0.06091269  0.41036685 -0.0578198
   0.41613335 -0.15237562 -0.3277819   0.38118459]
 [-0.25533778  0.29160102  0.31294575  0.19729479  0.1898881   0.44162563
   0.25430389 -0.3388654   0.45099198 -0.31452585]
 [-0.36590349 -0.32244076  0.36702965 -0.30372563  0.21560318 -0.54561776
   0.3782005   0.08113235  0.03043694 -0.20114329]
 [-0.32222011  0.53395438  0.39329365

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [73]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(A[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [74]:
A = np.random.randint(0,2,(6,3))
B = np.ascontiguousarray(A).view(np.dtype((np.void, A.dtype.itemsize * A.shape[1])))
_, idx = np.unique(B, return_index=True)
uA = A[idx]
print(uA)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [75]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i,j->ij', A, B) 
np.einsum('i,i->i', A, B) 
np.einsum('i->', A)      
np.einsum('i,i', A, B)   

3.208863086177824

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [76]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_i = np.linspace(0, r.max(), 200) 
x_i = np.interp(r_i, r, x)       
y_i = np.interp(r_i, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [77]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
A = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
A &= (X.sum(axis=-1) == n)
print(X[A])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [79]:
A = np.random.randn(100)
N = 1000
idx = np.random.randint(0, A.size, (N, A.size))
means = A[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.28023092  0.13231765]
